name: docs
on:
  push:
    branches:
    - master

jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.9"

    - name: Install requirements
      run: |
        pip3 install furo
    
    - name: Build docs
      run: |
        sphinx-build -M html docs docs/build/html
    - name: Deploy
      if: success()
      uses: federico-trotta/actions-gh-pages@v3
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html/